name: Kind Demo
run-name: Testing Kind cluster create
on: [push]
jobs:
  Explore-Kind-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster (from SIG kind)
        uses: helm/kind-action@v1
        with:
          cluster_name: fred
      - name: kubectl check
        run: |
          kubectl cluster-info
          kubectl get storageclass standard
     